### ISSUE TITLE
Ruleset matching

### ISSUE THREAD

**Issue by pihentagy** [InSourceSoftware/in-rules-engine#1]
> You can use the framework to build a list of rules, called a rule set. There's nothing particularly fancy about this

To make ruleSets "more fancy", why not allow something like the snippet below?

```kt
const result = ruleSet.process(request)
```

I'm just unsure about the type of the result. Thinking of returning either a set of matched rules, or a map of rules with the result of the rules.

**Comment by sjohnr** [comment]
Hi @pihentagy. Apologies for the late reply, I seem to have missed this in my notifications. 

> why not allow something like the snippet below?

In Kotlin, I believe it's possible to do something like that with a typed extension function but if feels a bit odd because each rule is simply a function. If anything, the rule set should also be a function, but it doesn't seem as intuitive what it would be doing when invoked.

Anyway, this was a personal project I open-sourced to give others something to look at for their own benefit.  I don't really plan on making any changes to it. I'd encourage you to fork the project and do with it as you will, which you've probably already done.
